name: Create release and upload solution to Azure blob storage CI

on:
  push:
    branches: release

jobs:
  main:
    uses: BeverCRM/Workflow-Build-Release-Upload-CI/.github/workflows/build-release-upload-ci.yml@master
    secrets: inherit
    with:
      control-title: Password Field
      control-description: This control converts the string field into a password field.
      control-youtube-video-url: https://www.youtube.com/watch?v=JrtwpTn3YC8
